import React from "react";
import { Link } from "react-router-dom";
import {
  Heart,
  TrendingUp,
  Users,
  Home,
  Brain,
  Shield,
  Sparkles,
  DollarSign,
  Building2,
  Activity,
  Smile,
  GraduationCap,
  TreePine,
  ArrowLeft
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export default function CommunityBenefits() {
  const benefitCategories = [
    {
      title: "Health & Wellness Benefits",
      icon: <Heart className="w-8 h-8" />,
      color: "from-rose-500 to-pink-600",
      benefits: [
        {
          title: "Physical Health Improvements",
          icon: <Activity className="w-6 h-6" />,
          description: "Ice skating and recreational activities reduce stress and improve aerobic, cardiovascular, and muscular fitness. Regular physical activity in recreation centers promotes overall wellness through gym facilities, fitness classes, and sports programs.",
          stats: "Regular participation in physical activity reduces chronic disease risk"
        },
        {
          title: "Mental Health Support",
          icon: <Brain className="w-6 h-6" />,
          description: "Recreation centers combat social isolation and loneliness, which are significant public health concerns. Physical activity and sunlight exposure at recreation facilities have been shown to relax and improve mood.",
          stats: "Social isolation increases dementia risk by 50% and mortality risk by 26% in older adults"
        },
        {
          title: "Healthcare Cost Savings",
          icon: <Shield className="w-6 h-6" />,
          description: "Communities with active recreation programs see significant healthcare savings. The physical activity that occurs in parks and recreation facilities reduces healthcare costs through prevention of chronic diseases.",
          stats: "Sacramento saves almost $20 million annually in healthcare costs due to park-based physical activity"
        },
        {
          title: "Senior Health & Longevity",
          icon: <Heart className="w-6 h-6" />,
          description: "Approximately 25% of seniors aged 65+ are socially isolated. Community recreation centers provide crucial social connections and physical activity opportunities that reduce risks of dementia, heart disease, and stroke.",
          stats: "30% increased risk of coronary artery disease or stroke from social isolation"
        }
      ]
    },
    {
      title: "Economic Impact",
      icon: <TrendingUp className="w-8 h-8" />,
      color: "from-emerald-500 to-green-600",
      benefits: [
        {
          title: "Job Creation",
          icon: <Users className="w-6 h-6" />,
          description: "Recreation centers create diverse employment opportunities in administration, fitness leadership, facility management, and programming. The outdoor recreation economy alone accounts for 2.3% of U.S. GDP.",
          stats: "$1.2 trillion outdoor recreation economic output in 2023"
        },
        {
          title: "Property Value Increases",
          icon: <Home className="w-6 h-6" />,
          description: "Recreation facilities significantly boost nearby property values. Homebuyers are willing to pay 10% more for homes near parks and recreation facilities.",
          stats: "Properties near parks can see 60% value increases vs. 32% for properties outside park zones"
        },
        {
          title: "Tourism & Revenue",
          icon: <Sparkles className="w-6 h-6" />,
          description: "Sports facilities attract tournaments and events that bring visitors from neighboring regions. Sports tourism drives significant revenue increases through hotels, restaurants, and local business spending.",
          stats: "$150+ billion in economic activity generated by local parks and recreation agencies annually"
        },
        {
          title: "Local Business Growth",
          icon: <Building2 className="w-6 h-6" />,
          description: "Recreation centers support local economies by attracting new residents, retaining current residents, and drawing talented workers and retirees who prioritize quality-of-life amenities.",
          stats: "Talented workers and retirees more likely to locate in communities with recreation amenities"
        }
      ]
    },
    {
      title: "Social & Community Impact",
      icon: <Users className="w-8 h-8" />,
      color: "from-blue-500 to-indigo-600",
      benefits: [
        {
          title: "Community Connection & Third Spaces",
          icon: <Smile className="w-6 h-6" />,
          description: "Recreation centers serve as vital 'third spaces' outside of work and home where people can learn, destress, and organically connect. These facilities foster community pride and bring diverse groups together.",
          stats: "Social well-being and psychological health depend on community connection"
        },
        {
          title: "Youth Development",
          icon: <GraduationCap className="w-6 h-6" />,
          description: "Community arenas support youth through hockey leagues, figure skating, learn-to-skate programs, after-school activities, and summer camps. These programs develop healthy habits and provide safe recreation spaces.",
          stats: "Adolescents with access to recreation facilities are more physically active and less likely to be overweight"
        },
        {
          title: "Multigenerational Programming",
          icon: <Heart className="w-6 h-6" />,
          description: "Recreation centers offer inclusive programming for all ages, from youth sports to senior fitness classes, creating opportunities for cross-generational interaction and learning.",
          stats: "Recreation centers bridge healthcare access gaps and promote inclusivity"
        },
        {
          title: "Cultural & Educational Opportunities",
          icon: <TreePine className="w-6 h-6" />,
          description: "Beyond sports, recreation centers host cultural events, art and music classes, career training, and community celebrations that enrich local culture and provide affordable learning opportunities.",
          stats: "Community centers provide accessible educational and cultural programming"
        }
      ]
    }
  ];

  const keyStatistics = [
    {
      number: "$1.2T",
      label: "Outdoor recreation economic output (2023)",
      icon: <DollarSign className="w-6 h-6" />
    },
    {
      number: "50%",
      label: "Increased dementia risk from social isolation",
      icon: <Brain className="w-6 h-6" />
    },
    {
      number: "$150B+",
      label: "Annual economic activity from parks & rec",
      icon: <TrendingUp className="w-6 h-6" />
    },
    {
      number: "10%",
      label: "Property value premium near recreation facilities",
      icon: <Home className="w-6 h-6" />
    }
  ];

  return (
    <div className="min-h-screen bg-white">
      {/* Header Navigation */}
      <header className="sticky top-0 z-30 backdrop-blur-md bg-white/80 border-b shadow-sm">
        <div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl overflow-hidden shadow-lg">
              <img
                src="/ssicaalogo.png"
                alt="Salt Spring Island Community Arena Association Logo"
                className="w-full h-full object-cover"
              />
            </div>
            <div>
              <h1 className="font-bold text-lg leading-tight">Salt Spring Island Community Arena Association</h1>
              <p className="text-xs text-slate-500 -mt-0.5">Registered Non-Profit • Tax Receipts Available • For All Ages</p>
            </div>
          </div>
          <nav className="hidden md:flex gap-6 text-sm font-medium">
            <Link to="/" className="hover:text-sky-600 transition-colors">Home</Link>
            <Link to="/community-benefits" className="text-sky-600 font-semibold">Community Benefits</Link>
          </nav>
        </div>
      </header>

      {/* Hero Section */}
      <section className="py-16 bg-gradient-to-b from-sky-50 to-white">
        <div className="max-w-6xl mx-auto px-6">
          <Link to="/" className="inline-flex items-center gap-2 text-sky-600 hover:text-sky-700 mb-6 font-medium">
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </Link>

          <h1 className="text-5xl md:text-6xl font-bold text-slate-900 mb-6">
            Verified Community Benefits
          </h1>
          <p className="text-xl text-slate-700 max-w-4xl leading-relaxed">
            Research-backed evidence showing how recreation centers and community arenas create healthier,
            more connected, and economically vibrant communities. The data speaks for itself.
          </p>
        </div>
      </section>

      {/* Key Statistics */}
      <section className="py-12 bg-white">
        <div className="max-w-6xl mx-auto px-6">
          <h2 className="text-3xl font-bold text-center mb-8">By the Numbers</h2>
          <div className="grid md:grid-cols-4 gap-6">
            {keyStatistics.map((stat, i) => (
              <Card key={i} className="text-center">
                <CardContent className="pt-6 pb-6">
                  <div className="mx-auto w-12 h-12 rounded-xl bg-gradient-to-br from-sky-500/10 to-blue-600/10 flex items-center justify-center mb-3 text-sky-600">
                    {stat.icon}
                  </div>
                  <div className="text-3xl font-bold text-sky-600 mb-2">{stat.number}</div>
                  <p className="text-sm text-slate-600">{stat.label}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Main Benefits Sections */}
      {benefitCategories.map((category, categoryIndex) => (
        <section key={categoryIndex} className={`py-20 ${categoryIndex % 2 === 0 ? 'bg-slate-50' : 'bg-white'}`}>
          <div className="max-w-7xl mx-auto px-6">
            <div className="flex items-center gap-4 mb-12">
              <div className={`w-16 h-16 rounded-2xl bg-gradient-to-br ${category.color} text-white flex items-center justify-center shadow-lg`}>
                {category.icon}
              </div>
              <h2 className="text-4xl font-bold text-slate-900">{category.title}</h2>
            </div>

            <div className="grid md:grid-cols-2 gap-8">
              {category.benefits.map((benefit, i) => (
                <Card key={i} className="hover:shadow-xl transition-shadow duration-300">
                  <CardContent className="p-8">
                    <div className="flex items-start gap-4 mb-4">
                      <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${category.color} bg-opacity-10 flex items-center justify-center text-slate-700`}>
                        {benefit.icon}
                      </div>
                      <div className="flex-1">
                        <h3 className="text-xl font-bold text-slate-900 mb-3">{benefit.title}</h3>
                        <p className="text-slate-700 leading-relaxed mb-4">{benefit.description}</p>
                        <div className="bg-sky-50 border-l-4 border-sky-500 p-3 rounded">
                          <p className="text-sm font-semibold text-sky-900">{benefit.stats}</p>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>
      ))}

      {/* Research Sources */}
      <section className="py-16 bg-gradient-to-b from-white to-slate-50">
        <div className="max-w-6xl mx-auto px-6">
          <h2 className="text-3xl font-bold text-center mb-8">Research Sources</h2>
          <Card>
            <CardContent className="p-8">
              <p className="text-slate-700 mb-6">
                The information on this page is compiled from peer-reviewed research, government reports,
                and established industry organizations including:
              </p>
              <div className="grid md:grid-cols-2 gap-4 text-sm text-slate-600">
                <ul className="space-y-2">
                  <li>• U.S. Bureau of Economic Analysis</li>
                  <li>• National Recreation and Park Association</li>
                  <li>• JAMA Network (Journal of the American Medical Association)</li>
                  <li>• National Academies of Sciences, Engineering, and Medicine</li>
                </ul>
                <ul className="space-y-2">
                  <li>• BMC Public Health Research</li>
                  <li>• American Trails Organization</li>
                  <li>• Headwaters Economics</li>
                  <li>• Sports Facilities Advisory</li>
                </ul>
              </div>
              <p className="text-xs text-slate-500 mt-6 pt-6 border-t">
                All statistics and research findings cited on this page are from 2020-2025 publications
                and represent the most current available data on community recreation benefits.
              </p>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* Call to Action */}
      <section className="py-20 bg-gradient-to-b from-sky-600 to-blue-700 text-white">
        <div className="max-w-4xl mx-auto px-6 text-center">
          <h2 className="text-4xl font-bold mb-6">
            These Benefits Can Be Ours
          </h2>
          <p className="text-xl text-sky-100 mb-8 leading-relaxed">
            Every statistic, every health benefit, every economic impact described here can become reality
            for Salt Spring Island. The research is clear: community recreation centers transform lives and communities.
          </p>
          <div className="flex flex-wrap gap-4 justify-center">
            <Link to="/">
              <Button
                size="lg"
                className="rounded-full px-8 py-6 text-lg bg-white text-sky-700 hover:bg-sky-50 shadow-lg"
              >
                Support Our Arena
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-slate-900 text-white py-12">
        <div className="max-w-6xl mx-auto px-6">
          <div className="grid md:grid-cols-3 gap-8">
            <div>
              <h3 className="font-bold mb-4">Contact</h3>
              <p className="text-slate-400 text-sm">
                Salt Spring Island Community Arena Association<br />
                saltspringislandarena@gmail.com<br />
                Registered Non-Profit Society
              </p>
            </div>
            <div>
              <h3 className="font-bold mb-4">Quick Links</h3>
              <ul className="text-slate-400 text-sm space-y-2">
                <li><Link to="/" className="hover:text-white transition-colors">Home</Link></li>
                <li><Link to="/community-benefits" className="hover:text-white transition-colors">Community Benefits</Link></li>
              </ul>
            </div>
            <div>
              <h3 className="font-bold mb-4">Project Credits</h3>
              <p className="text-slate-400 text-sm">
                Architect: John Hemsworth<br />
                Hemsworth Architects<br />
                Inspired by Upper Skeena Rec Centre
              </p>
            </div>
          </div>

          <div className="border-t border-slate-800 mt-8 pt-8 text-center">
            <p className="text-slate-400 text-sm">
              © {new Date().getFullYear()} Salt Spring Island Community Arena Association
            </p>
            <p className="text-slate-500 text-xs mt-2">
              Building our community's future together
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
